<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NexusPOS.Sales.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../NexusPOS.SharedKernel/NexusPOS.SharedKernel.csproj" />
    <ProjectReference Include="../../POS/NexusPOS.POS/NexusPOS.POS.csproj" />
    <ProjectReference Include="../../Catalog/NexusPOS.Catalog/NexusPOS.Catalog.csproj" />
    <ProjectReference Include="../../Inventory/NexusPOS.Inventory/NexusPOS.Inventory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
